//
//  ViewController.swift
//  QuestTest
//
//  Created by Owen on 2020/12/28.
//

import UIKit

class ViewController: UIViewController {
    @IBOutlet weak var answerLabel: UILabel!
    @IBOutlet weak var questionLanel: UILabel!
    
    var questions = [Question]()
    var index = 0

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
       
        /*上課練習
        let question1 = Question(description: "拿鐵是加什麼", answer: "牛奶" )
        questions.append(question1)
        let question2 = Question(description: "摩卡是加什麼", answer: "巧克力" )
        questions.append(question2)
        let question3 = Question(description: "美式是加什麼", answer: "水")
        questions.append(question3)
        */
         let question1 = Question(description: "白糖梅子真稀奇 (打一食物)", answer: "元宵" )
         questions.append(question1)
         let question2 = Question(description: "愛好旅遊(打一成語)", answer: "喜出望外" )
         questions.append(question2)
         let question3 = Question(description: "兩點天上來(打一字)", answer: "關" )
         questions.append(question3)
         let question4 = Question(description: "小時像逗號，在水中玩耍長大跳得高，是捉蟲冠軍 (打一動物名)", answer: "青蛙" )
         questions.append(question4)
         let question5 = Question(description: "熒火蟲(打一中國地名)", answer: "昆明" )
         questions.append(question5)
         let question6 = Question(description: "四個晚上(打一字)", answer: "羅" )
         questions.append(question6)
         let question7 = Question(description: "小小東西，放在腋底有病沒病，看它肚皮(打一日常用品)", answer: "溫度計" )
         questions.append(question7)
         let question8 = Question(description: "逆水划船(打一成語)", answer: "力爭上游" )
         questions.append(question8)
         let question9 = Question(description: "白又方，嫩又香，能做菜，能煮湯，豆子是它爹和媽，它和爹媽不一樣(打一食物)", answer: "豆腐" )
         questions.append(question9)
         let question10 = Question(description: "上下一體(打一字)", answer: "卡" )
         questions.append(question10)
         let question11 = Question(description: "一個娃娃白又胖，頭上戴個瓜皮帽冬天地上靜靜坐，不怕冷來就怕熱(打一物)", answer: "雪人" )
         questions.append(question11)
         let question12 = Question(description: "入門無犬吠(打一字)", answer: "問" )
         questions.append(question12)
         let question13 = Question(description: "有風吹不動，它動就生風，若要不動它，待到起秋風(打一日常用品)", answer: "扇子" )
         questions.append(question13)
         let question14 = Question(description: "第二次握手(打一字)", answer: "觀" )
         questions.append(question14)
         let question15 = Question(description: "四通八達(打一成語)", answer: "頭頭是道" )
         questions.append(question15)
         let question16 = Question(description: "海上一隻鳥，跟著船兒跑衝浪去抓魚，不怕大風暴 (打一動物名)", answer: "海鷗" )
         questions.append(question16)
         let question17 = Question(description: "兄有債(打一字)", answer: "歌" )
         questions.append(question17)
         let question18 = Question(description: "有洞不見蟲，有巢不見峰，有絲不見蠶，撐傘不見人", answer: "藕" )
         questions.append(question18)
         let question19 = Question(description: "早不說晚不說(打一字)", answer: "許" )
         questions.append(question19)
         let question20 = Question(description: "有樣東西是個寶，垃圾堆是能找到(打一字)", answer: "土" )
         questions.append(question20)
         let question21 = Question(description: "一隻小蟲生得怪，嘴巴長在天靈蓋(打一字)", answer: "雖" )
         questions.append(question21)
         let question22 = Question(description: "神州念一統，兩地豈可分(打一字)", answer: "鞋" )
         questions.append(question22)
         let question23 = Question(description: "東方有戰亂(打一地名)", answer: "西安" )
         questions.append(question23)
         let question24 = Question(description: "上弦下弦星星點點 (打一字)", answer: "弱" )
         questions.append(question24)
         let question25 = Question(description: "上不在上，下不在下，人有它大，天沒它大(打一字)", answer: "一" )
         questions.append(question25)
         let question26 = Question(description: "秋波橫送，細語直傳(打一字)", answer: "罷" )
         questions.append(question26)
         let question27 = Question(description: "請君猜謎，不言不走，且站一旁，對著細想(打一字)", answer: "粗" )
         questions.append(question27)
         let question28 = Question(description: "青山兩邊低，八字在中間，有力支撐起，沒有一文錢(打一字)", answer: "窮" )
         questions.append(question28)
         let question29 = Question(description: "遇事不求人(打一成語)", answer: "自力更生" )
         questions.append(question29)
         let question30 = Question(description: "前前後後都要放在心上 (打一字)", answer: "總" )
         questions.append(question30)
         let question31 = Question(description: "千里之外有人家 (打一字)", answer: "驢" )
         questions.append(question31)
         let question32 = Question(description: "牛之頭，虎之尾，猜不著，別多嘴(打一字)", answer: "先" )
         questions.append(question32)
         let question33 = Question(description: "一個老師不說話，他的肚裡學問大你若有啥不明白，趕快就去請教它(打一學習用品)", answer: "字典" )
         questions.append(question33)
         let question34 = Question(description: "盲人摸象(打一成語)", answer: "不識大體" )
         questions.append(question34)
         let question35 = Question(description: "四四方方一寶寶，洗澡時候發泡泡你越洗來它越小，等你洗完不見了(打一生活用品)", answer: "肥皂" )
         questions.append(question35)
         let question36 = Question(description: "蜜餞黃連(打一成語)", answer: "同甘共苦" )
         questions.append(question36)
         let question37 = Question(description: "快刀斬亂麻(打一成語)", answer: "迎刃而解" )
         questions.append(question37)
         let question38 = Question(description: "翹翹板(打一成語)", answer: "此起彼落" )
         questions.append(question38)
         let question39 = Question(description: "遠看兩個零，近看兩個零有人用了行不得，有人不用不得行(打一日常用品)", answer: "眼鏡" )
         questions.append(question39)
         let question40 = Question(description: "山鄉水、水鄉山，而今處處變了樣(打一字)", answer: "綠" )
         questions.append(question40)
         let question41 = Question(description: "節日的焰火(打一成語)", answer: "五彩繽紛" )
         questions.append(question41)
         let question42 = Question(description: "逆水划船(打一成語)", answer: "激流勇進" )
         questions.append(question42)
         let question43 = Question(description: "傘兵(打一成語)", answer: "從天而降" )
         questions.append(question43)
         let question44 = Question(description: "一個大哥三隻眼，每天路口來值班人們看著它眼色，要是亂闖出危險(打一交通設施)", answer: "紅綠燈" )
         questions.append(question44)
         let question45 = Question(description: "仙樂(打一成語)", answer: "不同凡響" )
         questions.append(question45)
         let question46 = Question(description: "沙漠一隻船，船上載大山遠看像筆架，近看一身氈 (打一動物名)", answer: "駱駝" )
         questions.append(question46)
         let question47 = Question(description: "零存整取(打一成語)", answer: "積少成多" )
         questions.append(question47)
         let question48 = Question(description: "一盞紅燈圓又大，每天早晨空中掛光芒四射照大地，到了晚上不見它(打一自然界景物)", answer: "太陽" )
         questions.append(question48)
         let question49 = Question(description: "打邊鼓(打一成語)", answer: "旁敲側擊" )
         questions.append(question49)
         let question50 = Question(description: "超級好牙刷(打一成語)", answer: "一毛不拔" )
         questions.append(question50)
         let question51 = Question(description: "屁股一冒煙，直衝九重天人造小星星，靠它送上天(打一現代科技物)", answer: "火箭" )
         questions.append(question51)
         let question52 = Question(description: "一隻八寶袋，樣樣都能裝能裝棉和紗，能裝鐵和鋼(打一日常用品)", answer: "針線包" )
         questions.append(question52)
         let question53 = Question(description: "百歲老人(打一中草藥名)", answer: "白頭翁" )
         questions.append(question53)
         let question54 = Question(description: "電鋸開木頭(打一成語)", answer: "當機立斷" )
         questions.append(question54)
         let question55 = Question(description: "有面無口，有腳無手聽人講話，陪人吃酒(打一日常用品)", answer: "桌子" )
         questions.append(question55)
         let question56 = Question(description: "空對空導彈(打一成語)", answer: "見機行事" )
         questions.append(question56)
         let question57 = Question(description: "說你呆，你不呆，推你一下你一歪叫你躺下去睡覺，你卻仍然站起來(打一玩具)", answer: "不倒翁" )
         questions.append(question57)
         let question58 = Question(description: "身穿大紅袍，串起像鞭炮你咬它，它不叫，它咬你，汗直冒(打一蔬菜)", answer: "紅尖椒" )
         questions.append(question58)
         let question59 = Question(description: "魯達當和尚(打一成語)", answer: "半路出家" )
         questions.append(question59)
         let question60 = Question(description: "婁阿鼠問卦(打一成語)", answer: "做賊心虛" )
         questions.append(question60)
         let question61 = Question(description: "長方形的紅色糕，不能吃來不能咬商店裡面買不著，建築工地能看到(打一建築材料)", answer: "紅磚" )
         questions.append(question61)
         let question62 = Question(description: "有時圓圓，有時彎彎;有時像香蕉，有時像小船(打一自然界景物)", answer: "月亮" )
         questions.append(question62)
         let question63 = Question(description: "舉重比賽(打一成語)", answer: "斤斤計較" )
         questions.append(question63)
         let question64 = Question(description: "一物生得妙，看了哈哈笑矮子能變高，瘦子能變胖(打一娛樂用品)", answer: "哈哈鏡" )
         questions.append(question64)
         let question65 = Question(description: "時到日落人方歸 (打一字)", answer: "付" )
         questions.append(question65)
         let question66 = Question(description: "麻屋子，紅帳子，裡面睡個白胖子(打一食物)", answer: "花生" )
         questions.append(question66)
         let question67 = Question(description: "一間小房子，有門沒有窗送你上下樓，每天忙不停(打一交通工具)", answer: "電梯" )
         questions.append(question67)
         let question68 = Question(description: "一間房屋四四方，沒有門來有扇窗裡面唱歌又演戲，一天到晚變花樣(打一電器)", answer: "電視機" )
         questions.append(question68)
         let question69 = Question(description: "左手五個，左手五個拿去十個，還剩十個(打一日常用品)", answer: "手套" )
         questions.append(question69)
         let question70 = Question(description: "四角方方，常隨常往傷風咳嗽，數它最忙(打一日常用品)", answer: "手帕" )
         questions.append(question70)
         let question71 = Question(description: "半個西瓜樣，口朝上面擱上頭不怕水，下頭不怕火(打一日常用品)", answer: "鍋" )
         questions.append(question71)
         let question72 = Question(description: "中間是火山，四邊是大海海裡寶貝多，快快撈上來(打一日常用品)", answer: "火鍋" )
         questions.append(question72)
         let question73 = Question(description: "紅娘子，上高樓，心裡疼，眼淚流(打一日常用品名)", answer: "蠟燭" )
         questions.append(question73)
         let question74 = Question(description: "前面來隻船，舵手在上邊，來時下小雨，走後路已乾(打一日常用品)", answer: "熨斗" )
         questions.append(question74)
         let question75 = Question(description: "鼻子朝天，嘴巴朝地敲它一錘，驚天動地(打一日常用品)", answer: "大鐘" )
         questions.append(question75)
         let question76 = Question(description: "啞巴打手勢(打一成語)", answer: "不言而喻" )
         questions.append(question76)
         let question77 = Question(description: "你坐我不坐，我行你不行你睡躺得平，我睡站到明 (打一動物名)", answer: "馬" )
         questions.append(question77)
         let question78 = Question(description: "金鉤吊銀圈，姐妹隔座山若要來相會，需到天色晚(打一日常用品)", answer: "耳環" )
         questions.append(question78)
         let question79 = Question(description: "生在山崖，落在人家，涼水澆背，千刀萬剮(打一日用品)", answer: "磨刀石" )
         questions.append(question79)
         let question80 = Question(description: "薄薄一張口，能啃硬骨頭吃肉不喝湯，吃瓜不嚼豆(打一日常用品)", answer: "菜刀" )
         questions.append(question80)
         let question81 = Question(description: "有硬有軟，有長有寬白天空閒，夜晚上班(打一日常用品)", answer: "床" )
         questions.append(question81)
         let question82 = Question(description: "白天一起玩，夜間一塊眠到老不分散，人誇好姻緣 (打一動物名)", answer: "鴛鴦" )
         questions.append(question82)
         let question83 = Question(description: "猛將百餘人，無事不出城出城就放火，引火自燒身(打一日常用品)", answer: "火柴" )
         questions.append(question83)
         let question84 = Question(description: "需要一半，留下一半 (打一字)", answer: "雷" )
         questions.append(question84)
         let question85 = Question(description: "有位小姑娘，身穿黃衣裳誰要欺負她，她就戳一槍 (打一動物名)", answer: "黃蜂" )
         questions.append(question85)
         let question86 = Question(description: "身小力不小，團結又勤勞有時搬糧食，有時挖地道 (打一動物名)", answer: "螞蟻" )
         questions.append(question86)
         let question87 = Question(description: "一隻雀，飛上桌，捏尾巴，跳下河(打日常用品)", answer: "湯匙" )
         questions.append(question87)
         let question88 = Question(description: "頭頂兩隻角，身背一隻鑊只怕曬太陽，不怕大雨落 (打一動物名)", answer: "蝸牛" )
         questions.append(question88)
         let question89 = Question(description: "穿著大紅袍，頭戴鐵甲帽叫叫我阿公，捉捉我不牢 (打一動物名)", answer: "蜈蚣" )
         questions.append(question89)
         let question90 = Question(description: " 胖子開會(打一中國地名)", answer: "合肥" )
         questions.append(question90)
         let question91 = Question(description: " 一塊板兒搭兩旁，一頭低來一頭高小朋友們都愛它，一上一下真好玩(打一娛樂設施)", answer: "蹺蹺板" )
         questions.append(question91)
         let question92 = Question(description: "一隻黑狗，不叫不吼 (打一字)", answer: "默" )
         questions.append(question92)
         let question93 = Question(description: "頭胖腳掌大，像個大傻瓜四肢短又粗，愛穿黑大褂 (打一動物名)", answer: "熊" )
         questions.append(question93)
         let question94 = Question(description: "格外大方 (打一字)", answer: "回" )
         questions.append(question94)
         let question95 = Question(description: "鼻子像鉤子，耳朵像扇子大腿像柱子，尾巴像鞭子 (打一動物名)", answer: "象" )
         questions.append(question95)
         let question96 = Question(description: "一隻牛(打一字)", answer: "生" )
         questions.append(question96)
         let question97 = Question(description: "什麼水取之不盡用之不竭？", answer: "口水" )
         questions.append(question97)
         let question98 = Question(description: "遠看像黃球，近看毛茸茸嘰嘰嘰嘰叫，最愛吃小蟲 (打一動物名)", answer: "小雞" )
         questions.append(question98)
         let question99 = Question(description: "小姑娘(打一字)", answer: "妙" )
         questions.append(question99)
         let question100 = Question(description: "身上滑膩膩，喜歡鑽河底張嘴吐泡泡，可以測天氣 (打一動物名)", answer: "泥鰍" )
         questions.append(question100)
         let question101 = Question(description: "元宵之後柳吐芽 (打一成語)", answer: "節外生枝" )
         questions.append(question101)
         let question102 = Question(description: "層雲隱去月當頭 (打一字)", answer: "屑" )
         questions.append(question102)
         let question103 = Question(description: "趕製元宵閒不住 (五字口語)", answer: "忙得團團轉" )
         questions.append(question103)
        let question104 = Question(description: "空中碼頭謎底 (打一中國港口)", answer: "連雲港" )
         questions.append(question104)
         let question105 = Question(description: "園外隱約聞猿啼，星月小橋聽蕭聲 (節日紀念日)", answer: "元宵節" )
         questions.append(question105)
         let question106 = Question(description: "此時此地 (劇目)", answer: "元宵謎" )
         questions.append(question106)
         let question107 = Question(description: "一夜魚龍舞 (民俗風俗詞語)", answer: "元宵燈會" )
         questions.append(question107)
         let question108 = Question(description: "離別四十年，本聚在元宵(打一字)", answer: "舞" )
         questions.append(question108)
         let question109 = Question(description: "元宵節後 (打一字)", answer: "完" )
         questions.append(question109)
         let question110 = Question(description: "山上還有山 (打一字)", answer: "出" )
         questions.append(question110)
         let question111 = Question(description: "杜鵑啼血(打一中草藥名)", answer: "紅花" )
         questions.append(question111)
         let question112 = Question(description: "外面冷冰冰，裡面熱心腸，一夜到天亮，肚裡還不涼(打一日常用品)", answer: "暖壺" )
         questions.append(question112)
         let question113 = Question(description: "十張口，一顆心 (打一字)", answer: "思" )
         questions.append(question113)
         let question114 = Question(description: "說它小，下邊大，說它大，上邊小 (打一字)", answer: "尖" )
         questions.append(question114)
         let question115 = Question(description: "家中添一口 (打一字)", answer: "豪" )
         questions.append(question115)
         let question116 = Question(description: "長得像黃菊，引誘小魚蝦觸手捕食物，舞爪又張牙物名)", answer: "海葵" )
         questions.append(question116)
         let question117 = Question(description: "自小在一起，目前少聯繫 (打一字)", answer: "省" )
         questions.append(question117)
         let question118 = Question(description: "點點成金 (打一字)", answer: "全" )
         questions.append(question118)
         let question119 = Question(description: "兄弟七八千，住在屋簷邊日日做漿賣，漿汁更值錢物名)", answer: "蜂" )
         questions.append(question119)
         let question120 = Question(description: "一人一張口，下面長隻手 (打一字)", answer: "拿" )
         questions.append(question120)
         let question121 = Question(description: "元宵燈火已闌珊 (謙辭禮貌用語)", answer: "望多關照" )
         questions.append(question121)
         let question122 = Question(description: "種花要除草，一人來一刀 (打一字)", answer: "化" )
         questions.append(question122)
         let question123 = Question(description: "帶著平頂帽，身穿圓筒襖，雖然一隻眼，暗中逞英豪(打一日常用品)", answer: "手電筒" )
         questions.append(question123)
         let question124 = Question(description: "個兒高又大，脖子似吊塔和氣又善良，從來不打架 (打一動物名)", answer: "長頸鹿" )
         questions.append(question124)
         let question125 = Question(description: "存心不讓出大門，你說煩人不煩人 (打一字)", answer: "悶" )
         questions.append(question125)
         let question126 = Question(description: "一隻狗，兩個口，誰遇它誰發愁 (打一字)", answer: "哭" )
         questions.append(question126)
         let question127 = Question(description: "皇帝新衣 (打一字)", answer: "襲" )
         questions.append(question127)
         let question128 = Question(description: "一點水準 (打一字)", answer: "淮" )
         questions.append(question128)
         let question129 = Question(description: "七十二小時 (打一字)", answer: "晶" )
         questions.append(question129)
         let question130 = Question(description: "一月一日非今天 (打一字)", answer: "明" )
         questions.append(question130)
         let question131 = Question(description: "綜合門市 (打一字)", answer: "鬧" )
         questions.append(question131)
         let question132 = Question(description: "皮白腰兒細，會爬又會飛木頭當糧食，專把房屋毀物名) (打一動", answer: "白蟻" )
         questions.append(question132)
         let question133 = Question(description: "覺醒了的大地(打一地名)", answer: "蘇州" )
         questions.append(question133)
         let question134 = Question(description: "守門員 (打一字)", answer: "閃" )
         questions.append(question134)
         let question135 = Question(description: "半青半紫 (打一字)", answer: "素" )
         questions.append(question135)
         let question136 = Question(description: "身殘心不殘 (打一字)", answer: "息" )
         questions.append(question136)
         let question137 = Question(description: "千里丟一，百里丟 (打一字)", answer: "伯" )
         questions.append(question137)
         let question138 = Question(description: "一人 (打一字)", answer: "大" )
         questions.append(question138)
         let question139 = Question(description: "一人一張口，口下長隻手(打一字)", answer: "拿" )
         questions.append(question139)
         let question140 = Question(description: "一人在內(打一字)", answer: "肉" )
         questions.append(question140)
         let question141 = Question(description: "一口吃掉牛尾巴(打一字)", answer: "告" )
         questions.append(question141)
         let question142 = Question(description: "一斗米(打一字)", answer: "料" )
         questions.append(question142)
         let question143 = Question(description: "一百減一 (打一字)", answer: "白" )
         questions.append(question143)
         let question144 = Question(description: "一夜又一夜(打一字)", answer: "多" )
         questions.append(question144)
         let question145 = Question(description: "一個人搬兩個土 (打一字)", answer: "佳" )
         questions.append(question145)
         let question146 = Question(description: "一個禮拜 (打一字)", answer: "旨" )
         questions.append(question146)
         let question147 = Question(description: "一個鐵娃娃，沒爸沒有媽生來最聰明，幹啥他都行 (打一現代科技物)", answer: "機器人" )
         questions.append(question147)
         let question148 = Question(description: "一家十一口(打一字)", answer: "吉" )
         questions.append(question148)
         let question149 = Question(description: "什麼東西只能加不能減？", answer: "年齡" )
         questions.append(question149)
         let question150 = Question(description: "一隻狗四個口(打一字)", answer: "器" )
         questions.append(question150)
         let question151 = Question(description: "一邊是紅，一邊是綠，一邊怕風，一邊怕雨(打一字)", answer: "秋" )
         questions.append(question151)
         let question152 = Question(description: "背景分明(打一中國地名)", answer: "北京" )
         questions.append(question152)
         let question153 = Question(description: "七人頭上長了草(打一字)", answer: "花" )
         questions.append(question153)
         let question154 = Question(description: "五月既望(打一中草藥名)", answer: "半夏" )
         questions.append(question154)
         let question155 = Question(description: "人不在其位 (打一字)", answer: "立" )
         questions.append(question155)
         let question156 = Question(description: "九九歸一(打一中草藥名)", answer: "百合" )
         questions.append(question156)
         let question157 = Question(description: "八十八 (打一字)", answer: "米" )
         questions.append(question157)
         let question158 = Question(description: "東南北(打一中國地名)", answer: "西藏" )
         questions.append(question158)
         let question159 = Question(description: "刀出鞘(打一字)", answer: "力" )
         questions.append(question159)
         let question160 = Question(description: "三口重疊，莫把品字猜 (打一字)", answer: "目" )
         questions.append(question160)
         let question161 = Question(description: "三張紙(打一字)", answer: "順" )
         questions.append(question161)
         let question162 = Question(description: "上下串通(打一字)", answer: "卡" )
         questions.append(question162)
         let question163 = Question(description: "雨落在橫山上(打一字)", answer: "雪" )
         questions.append(question163)
         let question164 = Question(description: "五十對耳朵 (打一字)", answer: "陌" )
         questions.append(question164)
         let question165 = Question(description: "六十不足，八十有餘(打一字)" , answer: "平" )
         questions.append(question165)
         let question166 = Question(description: "膚淺之談(打一中草藥名)", answer: "陳皮" )
         questions.append(question166)
         let question167 = Question(description: "公而忘私(打一字)", answer: "八" )
         questions.append(question167)
         let question168 = Question(description: "雪蓋冰河銀(打一字)", answer: "川" )
         questions.append(question168)
         let question169 = Question(description: "夫人何處去(打一字)", answer: "二" )
         questions.append(question169)
         let question170 = Question(description: "太陽西邊下，月兒東邊掛(打一字)", answer: "明" )
         questions.append(question170)
         let question171 = Question(description: "心如刀刺(打一字)", answer: "必" )
         questions.append(question171)
         let question172 = Question(description: "手提包(打一字)", answer: "抱" )
         questions.append(question172)
         let question173 = Question(description: "日復一日(打一字)", answer: "昌" )
         questions.append(question173)
         let question174 = Question(description: "水上工程(打一字)", answer: "汞" )
         questions.append(question174)
         let question175 = Question(description: "花滿海灣香(打一地名)", answer: "香港" )
         questions.append(question175)
         let question176 = Question(description: "半個月亮(打一字)", answer: "胖" )
         questions.append(question176)
         let question177 = Question(description: "天上無二，合去一口，家家都有(打一字)", answer: "人" )
         questions.append(question177)
         let question178 = Question(description: "鮫人揮淚(打一中草藥名)", answer: "珍珠散" )
         questions.append(question178)
         let question179 = Question(description: "半真半假(打一字)", answer: "值" )
         questions.append(question179)
         let question180 = Question(description: "古時候的月亮(打一字)", answer: "胡" )
         questions.append(question180)
         let question181 = Question(description: "左有十八，右有十八，二四得八，一八得八(打一字)", answer: "樊" )
         questions.append(question181)
         let question182 = Question(description: "有心得志(打一字)", answer: "士" )
         questions.append(question182)
         let question183 = Question(description: "有目共睹 (打一字)", answer: "者" )
         questions.append(question183)
         let question184 = Question(description: "有兩個動物，一個在水里，一個在山上 (打一字)", answer: "鮮" )
         questions.append(question184)
         let question185 = Question(description: "圓規畫雞蛋(打一地名)", answer: "太原" )
         questions.append(question185)
         let question186 = Question(description: "一加一(打一字)", answer: "王" )
         questions.append(question186)
         let question187 = Question(description: "大家都笑你齊(打一地名)", answer: "齊哈爾" )
         questions.append(question187)
         let question188 = Question(description: "千里戈壁(打一地名)", answer: "長沙" )
         questions.append(question188)
         let question189 = Question(description: "一口咬定(打一字)", answer: "交" )
         questions.append(question189)
         let question190 = Question(description: "什麼雞沒有翅膀？", answer: "田雞" )
         questions.append(question190)
         let question191 = Question(description: "四季花開(打一地名)", answer: "長春" )
         questions.append(question191)
         let question192 = Question(description: "打斷念頭(打一字)", answer: "心" )
         questions.append(question192)
         let question193 = Question(description: "海上綠洲(打一地名)", answer: "青島" )
         questions.append(question193)
         let question194 = Question(description: "稀世珍寶(打一中草藥名)", answer: "金不換" )
         questions.append(question194)
         let question195 = Question(description: "如箭在弦(打一字)", answer: "引" )
         questions.append(question195)
         let question196 = Question(description: "全面整頓(打一地名)", answer: "大理" )
         questions.append(question196)
         let question197 = Question(description: "兄有債(打一字)", answer: "歌" )
         questions.append(question197)
         let question198 = Question(description: "金鈿遍野(打一中草藥名)", answer: "地黃" )
         questions.append(question198)
         let question199 = Question(description: "一寸光陰一寸金(打一中國地名)", answer: "貴陽" )
         questions.append(question199)
         let question200 = Question(description: "巨輪出海(打一中國地名)", answer: "杭州" )
         questions.append(question200)
         let question201 = Question(description: "後來者居上(打一電影片名)", answer: "超人" )
         questions.append(question201)
         let question202 = Question(description: "誇誇其談(打一中國地名)", answer: "海口" )
         questions.append(question202)
         let question203 = Question(description: "永久太平(打一中國地名)", answer: "長安" )
         questions.append(question203)
         let question204 = Question(description: "藍色之洋(打一中國地名)", answer: "青海" )
         questions.append(question204)
         let question205 = Question(description: "不冷不熱的地方(打一中國地名)", answer: "溫州" )
         questions.append(question205)
         let question206 = Question(description: "寶樹叢叢謎底(打一中國地名)", answer: "吉林" )
         questions.append(question206)
         let question207 = Question(description: "羊上法庭(打一中國地名)", answer: "瀋陽" )
         questions.append(question207)
         let question208 = Question(description: "拿槍的兵(打一中國地名)", answer: "武漢" )
         questions.append(question208)
         let question209 = Question(description: "不知道(打一中草藥名)", answer: "生地" )
         questions.append(question209)
         let question210 = Question(description: "講故事(打一中草藥名)", answer: "白前" )
         questions.append(question210)
         let question211 = Question(description: "王先生，白小姐，坐在石頭上(打一字)", answer: "碧" )
         questions.append(question211)
        //隨機
        questions.shuffle()
        
        questionLanel.text = questions[index].description
        answerLabel.text = ""
    }

    @IBAction func showAnswer(_ sender: Any) {
        answerLabel.text = questions[index].answer
    }
    
    @IBAction func nextQuestion(_ sender: Any){
     /*
         //到最後一題就結束
      if index < questions.count - 1
    {
        index = index + 1
        questionLanel.text = questions[index].description
        answerLabel.text = ""
    }
      */
        // 回到第一題
        index = index + 1
        if index == questions.count{
        index = 0
    }
        questionLanel.text = questions[index].description
        answerLabel.text = ""
    }
}
